version: '3.5'

services:
  frontend:
    build:
      context: ./frontend
    container_name: docker-next
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mynetwork
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile  # Specify the location of the Dockerfile
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; cd app; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://root:123456@db:5432/books
    depends_on:
      - db
    networks:
      - mynetwork
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=books
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
